Popular_ebnerd_demo_x1:
    batch_size: 8192
    dataset_id: ebnerd_demo_x1_popular
    debug_mode: false
    feature_config: null
    group_id: impression_id
    metrics: [avgAUC, MRR, NDCG(k=5)]
    model: PopularRanker
    num_workers: 3
    seed: 20242025
    verbose: 1
