base_config: ./config/base_config/
base_expid: PopPredictor_default #TO CHECK
dataset_id: ebnerd_demo_x1_pop_pr

dataset_config:
  ebnerd_demo_x1_pop_pr:
    data_root: ./data/
    data_format: csv
    train_data: ./data/Ebnerd_demo_contrastive64_x1_PopPredictor/train.csv
    valid_data: ./data/Ebnerd_demo_contrastive64_x1_PopPredictor/valid.csv
    test_data: ./data/Ebnerd_demo_contrastive64_x1_PopPredictor/valid.csv
    min_categr_count: 10
    data_block_size: 100000
    streaming: True
    feature_cols:
      - { name: impression_id, active: True, dtype: int, type: meta, remap: False }
      - { name: article_id, active: True, dtype: str, type: categorical }
      - { name: article_type, active: True, dtype: str, type: categorical }
      - { name: ner_clusters, active: True, dtype: str, type: sequence, splitter: ^, max_len: 5, padding: pre }
      - { name: topics, active: True, dtype: str, type: sequence, splitter: ^, max_len: 5, padding: pre }
      - { name: category, active: True, dtype: str, type: categorical }
      - { name: subcategory, active: True, dtype: str, type: sequence, splitter: ^, max_len: 5, padding: pre }
      - { name: sentiment_score, active: False, dtype: float, type: numeric, fill_na: 0 }
      - { name: sentiment_label, active: True, dtype: str, type: categorical }
      - { name: subcat1, active: True, dtype: str, type: categorical }
      - { name: publish_days, active: True, dtype: str, type: categorical }
      - { name: publish_hours, active: True, dtype: str, type: categorical }
      - { name: impression_hour, active: True, dtype: str, type: categorical }
      - { name: impression_weekday, active: True, dtype: str, type: categorical }
      - { name: pulish_3day, active: True, dtype: str, type: categorical }
      - { name: pulish_7day, active: True, dtype: str, type: categorical }
      - { name: article_id_img, active: True, dtype: str, type: categorical, freeze_emb: True,
          preprocess: "copy_from(article_id)", pretrain_dim: 64, pretrained_emb: "./data/Ebnerd_demo_contrastive64_x1_PopPredictor/image_emb_dim64.npz",
          pretrain_usage: "init", min_categr_count: 1 }
      - { name: article_id_text, active: True, dtype: str, type: categorical, freeze_emb: True,
          preprocess: "copy_from(article_id)", pretrain_dim: 64, pretrained_emb: "./data/Ebnerd_demo_contrastive64_x1_PopPredictor/contrastive_emb_dim64.npz",
          pretrain_usage: "init", min_categr_count: 1 }
    label_col: { name: click, dtype: float }


tuner_space:
  model_root: './checkpoints/'
  embedding_dim: 64
  embedding_regularizer: 0.001
  net_dropout: 0.3
  net_regularizer: 0.0001
  batch_norm: False
  learning_rate: 0.001
  optimizer: adam
  loss: binary_crossentropy
  batch_size: 15000
  seed: 20242025
  group_id: impression_id
  dnn_hidden_units: [ [ 512, 256, 128 ] ]
  dnn_activations: ReLU
  metrics: [ [ avgAUC, MRR, NDCG(k=5) ] ]
  monitor: avgAUC